#!/bin/bash
if pgrep -f "gpu-screen-recorder" >/dev/null || pgrep -f "WebcamOverlay" >/dev/null; then
  echo '{"text": "REC", "class": "recording", "alt": "recording"}'
else
  echo '{"text": "", "class": "", "alt": ""}'
fi
