#!/bin/bash

if [[ -z $1 && $1 != "CNCLD" ]]; then
  echo "Usage: niri-theme-set <theme-name>"
  exit 1
fi

THEMES_DIR="$HOME/.config/themes/"
CURRENT_THEME_DIR="$HOME/.config/current-theme"

THEME_NAME=$(echo "$1" | sed -E 's/<[^>]+>//g' | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
THEME_PATH="$THEMES_DIR/$THEME_NAME"

# Check if the theme entered exists
if [[ ! -d "$THEME_PATH" ]]; then
  echo "Theme '$THEME_NAME' does not exist in $THEMES_DIR"
  exit 1
fi

# Update theme symlinks
ln -nsf "$THEME_PATH" "$CURRENT_THEME_DIR"

# Change background with theme
niri-theme-bg-next

# Restart components to apply new theme
if pgrep -x waybar >/dev/null; then
  pkill -x waybar >/dev/null 2>&1
  waybar >/dev/null 2>&1 &
fi
pkill -SIGUSR2 btop >/dev/null 2>&1
niri-restart-swayosd >/dev/null 2>&1
niri-restart-terminal >/dev/null 2>&1
makoctl reload

# Change gnome, browser, vscode, cursor themes

