#!/bin/bash

if [[ -f ~/.config/alacritty/alacritty.toml ]]; then
  touch ~/.config/alacritty/alacritty.toml
fi

if pgrep -x kitty; then
  killall -SIGUSR1 kitty >/dev/null 2>&1
fi

if pgrep -x ghostty; then
  killall -SIGUSR2 ghostty >/dev/null 2>&1
fi
